/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * The YSHAI backend API documentation. This API manages posts, teams, media, AI generation, moderation, analytics, billing, and more.
 * OpenAPI spec version: 1.0
 */
import type { AiReadyPayloadDtoArtifact } from './aiReadyPayloadDtoArtifact';

export interface AiReadyPayloadDto {
  /** Associated post id */
  postId: number;
  /** Which AI artifact is ready */
  artifact: AiReadyPayloadDtoArtifact;
}
