/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * The YSHAI backend API documentation. This API manages posts, teams, media, AI generation, moderation, analytics, billing, and more.
 * OpenAPI spec version: 1.0
 */

/**
 * Which AI artifact is ready
 */
export type AiReadyPayloadDtoArtifact = typeof AiReadyPayloadDtoArtifact[keyof typeof AiReadyPayloadDtoArtifact];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AiReadyPayloadDtoArtifact = {
  caption: 'caption',
  hashtags: 'hashtags',
  alt_text: 'alt_text',
} as const;
