/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * The YSHAI backend API documentation. This API manages posts, teams, media, AI generation, moderation, analytics, billing, and more.
 * OpenAPI spec version: 1.0
 */
import type { CreateWebhookDtoEvent } from './createWebhookDtoEvent';

export interface CreateWebhookDto {
  /** HTTPS endpoint to receive events */
  url: string;
  event: CreateWebhookDtoEvent;
  /** Shared secret to sign webhook payloads */
  secret: string;
}
