/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * The YSHAI backend API documentation. This API manages posts, teams, media, AI generation, moderation, analytics, billing, and more.
 * OpenAPI spec version: 1.0
 */
import type { GenerateCaptionDtoCount } from './generateCaptionDtoCount';

export interface GenerateCaptionDto {
  /** Prompt text for caption generation */
  prompt: string;
  /** Tone of the caption */
  tone?: string;
  /** Number of captions to generate */
  count: GenerateCaptionDtoCount;
}
