/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * The YSHAI backend API documentation. This API manages posts, teams, media, AI generation, moderation, analytics, billing, and more.
 * OpenAPI spec version: 1.0
 */
import type { GenerateHashtagsDtoCount } from './generateHashtagsDtoCount';

export interface GenerateHashtagsDto {
  /** Text to generate hashtags for */
  text: string;
  /** Number of hashtags to generate */
  count: GenerateHashtagsDtoCount;
}
