/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * The YSHAI backend API documentation. This API manages posts, teams, media, AI generation, moderation, analytics, billing, and more.
 * OpenAPI spec version: 1.0
 */
import type { InviteMemberDtoRole } from './inviteMemberDtoRole';

export interface InviteMemberDto {
  /** Email of the user to invite */
  email: string;
  /** Role to assign to the invited member */
  role: InviteMemberDtoRole;
}
