/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * The YSHAI backend API documentation. This API manages posts, teams, media, AI generation, moderation, analytics, billing, and more.
 * OpenAPI spec version: 1.0
 */

/**
 * Role to assign to the invited member
 */
export type InviteMemberDtoRole = typeof InviteMemberDtoRole[keyof typeof InviteMemberDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InviteMemberDtoRole = {
  admin: 'admin',
  editor: 'editor',
  viewer: 'viewer',
} as const;
