/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * The YSHAI backend API documentation. This API manages posts, teams, media, AI generation, moderation, analytics, billing, and more.
 * OpenAPI spec version: 1.0
 */

export type InvoiceResponseDtoCurrency = typeof InvoiceResponseDtoCurrency[keyof typeof InvoiceResponseDtoCurrency];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InvoiceResponseDtoCurrency = {
  SAR: 'SAR',
  USD: 'USD',
  EUR: 'EUR',
} as const;
