/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * The YSHAI backend API documentation. This API manages posts, teams, media, AI generation, moderation, analytics, billing, and more.
 * OpenAPI spec version: 1.0
 */

export type LinkAccountWithTokensDtoProvider = typeof LinkAccountWithTokensDtoProvider[keyof typeof LinkAccountWithTokensDtoProvider];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LinkAccountWithTokensDtoProvider = {
  x: 'x',
  instagram: 'instagram',
  linkedin: 'linkedin',
  tiktok: 'tiktok',
} as const;
