/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * The YSHAI backend API documentation. This API manages posts, teams, media, AI generation, moderation, analytics, billing, and more.
 * OpenAPI spec version: 1.0
 */
import type { LinkAccountWithTokensDtoProvider } from './linkAccountWithTokensDtoProvider';

export interface LinkAccountWithTokensDto {
  provider: LinkAccountWithTokensDtoProvider;
  providerAccountId: string;
  /** Short-lived access token from the provider */
  accessToken?: string;
  /** Long-lived refresh token from the provider */
  refreshToken?: string;
  /** Access token expiration (ISO 8601) */
  expiresAt?: string;
}
