/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * The YSHAI backend API documentation. This API manages posts, teams, media, AI generation, moderation, analytics, billing, and more.
 * OpenAPI spec version: 1.0
 */

export type MediaControllerUploadBody = {
  /** The media file (image or video) */
  file?: Blob;
  /** Optional: ID of the post to associate with */
  postId?: number;
};
