/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * The YSHAI backend API documentation. This API manages posts, teams, media, AI generation, moderation, analytics, billing, and more.
 * OpenAPI spec version: 1.0
 */
import type { MediaResponseDtoType } from './mediaResponseDtoType';

export interface MediaResponseDto {
  id: number;
  url: string;
  type: MediaResponseDtoType;
  orderIndex: number;
  createdAt: string;
  /** Associated post ID (if any) */
  postId: number;
}
