/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * The YSHAI backend API documentation. This API manages posts, teams, media, AI generation, moderation, analytics, billing, and more.
 * OpenAPI spec version: 1.0
 */
import type { Post } from './post';
import type { ModerationResultProvider } from './moderationResultProvider';
import type { ModerationResultVerdict } from './moderationResultVerdict';
import type { ModerationResultDetails } from './moderationResultDetails';
import type { ModerationResultCheckedAt } from './moderationResultCheckedAt';

export interface ModerationResult {
  /** Associated post */
  post: Post;
  provider: ModerationResultProvider;
  verdict: ModerationResultVerdict;
  /** Raw moderation details */
  details?: ModerationResultDetails;
  checkedAt: ModerationResultCheckedAt;
}
