/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * The YSHAI backend API documentation. This API manages posts, teams, media, AI generation, moderation, analytics, billing, and more.
 * OpenAPI spec version: 1.0
 */
import type { ModerationResultResponseDtoProvider } from './moderationResultResponseDtoProvider';
import type { ModerationResultResponseDtoVerdict } from './moderationResultResponseDtoVerdict';
import type { ModerationResultResponseDtoDetails } from './moderationResultResponseDtoDetails';

export interface ModerationResultResponseDto {
  id: number;
  provider: ModerationResultResponseDtoProvider;
  verdict: ModerationResultResponseDtoVerdict;
  /** @nullable */
  details?: ModerationResultResponseDtoDetails;
  checkedAt: string;
  postId: number;
}
