/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * The YSHAI backend API documentation. This API manages posts, teams, media, AI generation, moderation, analytics, billing, and more.
 * OpenAPI spec version: 1.0
 */
import type { NotificationResponseDtoType } from './notificationResponseDtoType';
import type { NotificationResponseDtoPayload } from './notificationResponseDtoPayload';
import type { NotificationResponseDtoLink } from './notificationResponseDtoLink';

export interface NotificationResponseDto {
  id: number;
  type: NotificationResponseDtoType;
  payload: NotificationResponseDtoPayload;
  read: boolean;
  createdAt: string;
  /** @nullable */
  link?: NotificationResponseDtoLink;
}
