/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * The YSHAI backend API documentation. This API manages posts, teams, media, AI generation, moderation, analytics, billing, and more.
 * OpenAPI spec version: 1.0
 */
import type { PostScheduledPayloadDto } from './postScheduledPayloadDto';
import type { PublishFailedPayloadDto } from './publishFailedPayloadDto';
import type { AiReadyPayloadDto } from './aiReadyPayloadDto';
import type { ApprovedPayloadDto } from './approvedPayloadDto';

/**
 * Type-specific payload for the notification
 * @nullable
 */
export type NotificationResponseDtoData = PostScheduledPayloadDto | PublishFailedPayloadDto | AiReadyPayloadDto | ApprovedPayloadDto | null;
