/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * The YSHAI backend API documentation. This API manages posts, teams, media, AI generation, moderation, analytics, billing, and more.
 * OpenAPI spec version: 1.0
 */
import type { NotificationResponseDtoLink } from './notificationResponseDtoLink';

/**
 * Optional URL for deep-linking to the related resource
 * @nullable
 */
export type NotificationResponseDtoLinkProperty = NotificationResponseDtoLink | null;
