/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * The YSHAI backend API documentation. This API manages posts, teams, media, AI generation, moderation, analytics, billing, and more.
 * OpenAPI spec version: 1.0
 */

export type NotificationResponseDtoType = typeof NotificationResponseDtoType[keyof typeof NotificationResponseDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationResponseDtoType = {
  post_scheduled: 'post_scheduled',
  publish_failed: 'publish_failed',
  ai_ready: 'ai_ready',
  approved: 'approved',
} as const;
