/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * The YSHAI backend API documentation. This API manages posts, teams, media, AI generation, moderation, analytics, billing, and more.
 * OpenAPI spec version: 1.0
 */
import type { PostResponseDtoStatus } from './postResponseDtoStatus';
import type { PostResponseDtoPublishedAt } from './postResponseDtoPublishedAt';

export interface PostResponseDto {
  id: number;
  contentAr: string;
  contentEn?: string;
  status: PostResponseDtoStatus;
  isRecurring: boolean;
  /** @nullable */
  publishedAt?: PostResponseDtoPublishedAt;
  createdAt: string;
  updatedAt: string;
  scheduleAt: string;
}
