/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * The YSHAI backend API documentation. This API manages posts, teams, media, AI generation, moderation, analytics, billing, and more.
 * OpenAPI spec version: 1.0
 */

export interface PostScheduledPayloadDto {
  /** Associated post id */
  postId: number;
  /** Target platform name (e.g., twitter, instagram) */
  platform: string;
  /** Scheduled publish time */
  scheduledAt: string;
}
