/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * The YSHAI backend API documentation. This API manages posts, teams, media, AI generation, moderation, analytics, billing, and more.
 * OpenAPI spec version: 1.0
 */

export interface RegisterDto {
  /**
   * User email address
   * @minLength 5
   * @maxLength 50
   */
  email: string;
  /**
   * Password for authentication
   * @minLength 6
   * @maxLength 100
   */
  password: string;
  /**
   * Full name of the user
   * @minLength 2
   * @maxLength 100
   */
  name: string;
  /** Timezone of the user */
  timezone: string;
  /** Preferred time format of the user */
  timeFormat: string;
}
