/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * The YSHAI backend API documentation. This API manages posts, teams, media, AI generation, moderation, analytics, billing, and more.
 * OpenAPI spec version: 1.0
 */

export interface SubscribeDto {
  /** Plan ID to subscribe to */
  planId: number;
  /** Payment method token or identifier */
  paymentMethod: string;
  /** Optional coupon code */
  couponCode?: string;
}
