/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * The YSHAI backend API documentation. This API manages posts, teams, media, AI generation, moderation, analytics, billing, and more.
 * OpenAPI spec version: 1.0
 */
import type { UpdatePostDtoStatus } from './updatePostDtoStatus';

export interface UpdatePostDto {
  /** Arabic content */
  contentAr?: string;
  /** English content */
  contentEn?: string;
  /** Scheduled date/time */
  scheduleAt?: string;
  /** Status */
  status?: UpdatePostDtoStatus;
  /** Is recurring? */
  isRecurring?: boolean;
  /** Team ID */
  teamId?: number;
  /** Social account IDs (multi-target) */
  socialAccountIds?: number[];
  /** Campaign ID */
  campaignId?: number;
  /** Template ID */
  templateId?: number;
}
