/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * The YSHAI backend API documentation. This API manages posts, teams, media, AI generation, moderation, analytics, billing, and more.
 * OpenAPI spec version: 1.0
 */
import type { UserResponseDtoRole } from './userResponseDtoRole';
import type { UserResponseDtoTimeFormat } from './userResponseDtoTimeFormat';

export interface UserResponseDto {
  id: number;
  email: string;
  name: string;
  role: UserResponseDtoRole;
  timezone?: string;
  isEmailVerified: boolean;
  language?: string;
  locale?: string;
  timeFormat?: UserResponseDtoTimeFormat;
  createdAt: string;
  updatedAt: string;
}
