/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */

export type AdminUserResponseDtoRole = typeof AdminUserResponseDtoRole[keyof typeof AdminUserResponseDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminUserResponseDtoRole = {
  user: 'user',
  admin: 'admin',
} as const;
