/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */

export interface AdminAuditLogResponseDto {
  id: number;
  action: string;
  entityType: string;
  entityId: string;
  timestamp: string;
}
