/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */

export type AuthControllerVerifyEmailParams = {
/**
 * Verification token from email
 */
token: string;
};
