/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */
import type { CreateWebhookDtoEvent } from './createWebhookDtoEvent';

export interface CreateWebhookDto {
  /** HTTPS endpoint to receive events */
  url: string;
  event: CreateWebhookDtoEvent;
  /** Shared secret to sign webhook payloads */
  secret: string;
}
