/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */
import type { CreatePostDtoStatus } from './createPostDtoStatus';

export interface CreatePostDto {
  /** Arabic content of the post */
  contentAr: string;
  /** English content of the post (optional) */
  contentEn?: string;
  /** Scheduled date and time for the post (ISO format) */
  scheduleAt: string;
  /** Status of the post */
  status?: CreatePostDtoStatus;
  /** Whether the post is part of a recurring schedule */
  isRecurring?: boolean;
  /** ID of the author (User) */
  authorId: number;
  /** ID of the team (optional) */
  teamId?: number;
  /** IDs of the social accounts to post to (optional, multi-target) */
  socialAccountIds?: number[];
  /** ID of the associated campaign (optional) */
  campaignId?: number;
  /** ID of the template used (optional) */
  templateId?: number;
}
