/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */

export type CreateWebhookDtoEvent = typeof CreateWebhookDtoEvent[keyof typeof CreateWebhookDtoEvent];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateWebhookDtoEvent = {
  postpublished: 'post.published',
  postfailed: 'post.failed',
  accountdisconnected: 'account.disconnected',
} as const;
