/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */
import type { GenerateHashtagsDtoCount } from './generateHashtagsDtoCount';

export interface GenerateHashtagsDto {
  /** Text to generate hashtags for */
  text: string;
  /** Number of hashtags to generate */
  count: GenerateHashtagsDtoCount;
}
