/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */

export interface GenerateAltTextDto {
  /** Image URL for alt text generation */
  imageUrl: string;
  /** Optional context for the image */
  context?: string;
}
