/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */
import type { GenerateCaptionDtoCount } from './generateCaptionDtoCount';

export interface GenerateCaptionDto {
  /** Prompt text for caption generation */
  prompt: string;
  /** Tone of the caption */
  tone?: string;
  /** Number of captions to generate */
  count: GenerateCaptionDtoCount;
}
