/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */
import type { InviteMemberDtoRole } from './inviteMemberDtoRole';

export interface InviteMemberDto {
  /** Email of the user to invite */
  email: string;
  /** Role to assign to the invited member */
  role: InviteMemberDtoRole;
}
