/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */
import type { InvoiceResponseDtoCurrency } from './invoiceResponseDtoCurrency';
import type { InvoiceResponseDtoStatus } from './invoiceResponseDtoStatus';
import type { InvoiceResponseDtoPaymentGatewayId } from './invoiceResponseDtoPaymentGatewayId';
import type { InvoiceResponseDtoPaymentMethod } from './invoiceResponseDtoPaymentMethod';
import type { InvoiceResponseDtoPaidAt } from './invoiceResponseDtoPaidAt';
import type { InvoiceResponseDtoDownloadedAt } from './invoiceResponseDtoDownloadedAt';
import type { InvoiceResponseDtoPdfUrl } from './invoiceResponseDtoPdfUrl';
import type { InvoiceResponseDtoMetadata } from './invoiceResponseDtoMetadata';

export interface InvoiceResponseDto {
  id: number;
  amount: number;
  currency: InvoiceResponseDtoCurrency;
  status: InvoiceResponseDtoStatus;
  /** @nullable */
  paymentGatewayId?: InvoiceResponseDtoPaymentGatewayId;
  /** @nullable */
  paymentMethod?: InvoiceResponseDtoPaymentMethod;
  issuedAt: string;
  /** @nullable */
  paidAt?: InvoiceResponseDtoPaidAt;
  /** @nullable */
  downloadedAt?: InvoiceResponseDtoDownloadedAt;
  /** @nullable */
  pdfUrl?: InvoiceResponseDtoPdfUrl;
  /** @nullable */
  metadata?: InvoiceResponseDtoMetadata;
}
