/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */

export type InvoiceResponseDtoStatus = typeof InvoiceResponseDtoStatus[keyof typeof InvoiceResponseDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InvoiceResponseDtoStatus = {
  paid: 'paid',
  unpaid: 'unpaid',
  refunded: 'refunded',
  failed: 'failed',
} as const;
