/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */

export type InvoiceResponseDtoCurrency = typeof InvoiceResponseDtoCurrency[keyof typeof InvoiceResponseDtoCurrency];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InvoiceResponseDtoCurrency = {
  SAR: 'SAR',
  USD: 'USD',
  EUR: 'EUR',
} as const;
