/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */

export type LinkAccountWithTokensDtoProvider = typeof LinkAccountWithTokensDtoProvider[keyof typeof LinkAccountWithTokensDtoProvider];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LinkAccountWithTokensDtoProvider = {
  x: 'x',
  instagram: 'instagram',
  linkedin: 'linkedin',
  tiktok: 'tiktok',
} as const;
