/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */

export type MediaResponseDtoType = typeof MediaResponseDtoType[keyof typeof MediaResponseDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MediaResponseDtoType = {
  image: 'image',
  video: 'video',
} as const;
