/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */

export type MediaControllerUploadBody = {
  /** The media file (image or video) */
  file?: Blob;
  /** Optional: ID of the post to associate with */
  postId?: number;
};
