/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */

export type ModerationResultResponseDtoProvider = typeof ModerationResultResponseDtoProvider[keyof typeof ModerationResultResponseDtoProvider];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModerationResultResponseDtoProvider = {
  gemini: 'gemini',
  custom: 'custom',
} as const;
