/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */

export type ModerationResultResponseDtoVerdict = typeof ModerationResultResponseDtoVerdict[keyof typeof ModerationResultResponseDtoVerdict];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModerationResultResponseDtoVerdict = {
  allowed: 'allowed',
  flagged: 'flagged',
  blocked: 'blocked',
} as const;
