/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */

export interface ModerateTextDto {
  /**
   * Arabic text to moderate
   * @maxLength 5000
   */
  text: string;
  /** Related post ID */
  postId: number;
}
