/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */
import type { NotificationResponseDtoPayload } from './notificationResponseDtoPayload';

/**
 * Optional arbitrary JSON data for the notification
 * @nullable
 */
export type NotificationResponseDtoData = NotificationResponseDtoPayload | null;
