/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */

export type NotificationType = typeof NotificationType[keyof typeof NotificationType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationType = {
  post_scheduled: 'post_scheduled',
  publish_failed: 'publish_failed',
  ai_ready: 'ai_ready',
  approved: 'approved',
} as const;
