/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */
import type { NotificationType } from './notificationType';
import type { NotificationMessageDto } from './notificationMessageDto';
import type { NotificationResponseDtoData } from './notificationResponseDtoData';
import type { NotificationResponseDtoLinkProperty } from './notificationResponseDtoLinkProperty';

export interface NotificationResponseDto {
  id: number;
  type: NotificationType;
  title: NotificationMessageDto;
  message: NotificationMessageDto;
  /**
   * Optional arbitrary JSON data for the notification
   * @nullable
   */
  data?: NotificationResponseDtoData;
  read: boolean;
  createdAt: string;
  /**
   * Optional URL for deep-linking to the related resource
   * @nullable
   */
  link?: NotificationResponseDtoLinkProperty;
}
