/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */
import type { NotificationResponseDtoLink } from './notificationResponseDtoLink';

/**
 * Optional URL for deep-linking to the related resource
 * @nullable
 */
export type NotificationResponseDtoLinkProperty = NotificationResponseDtoLink | null;
