/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */

export type PlanResponseDtoName = typeof PlanResponseDtoName[keyof typeof PlanResponseDtoName];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlanResponseDtoName = {
  Free: 'Free',
  Pro: 'Pro',
  Business: 'Business',
} as const;
