/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */
import type { PlanResponseDtoName } from './planResponseDtoName';
import type { PlanResponseDtoAiCreditsLimit } from './planResponseDtoAiCreditsLimit';

export interface PlanResponseDto {
  id: number;
  name: PlanResponseDtoName;
  priceMonthly: number;
  maxAccounts: number;
  aiCreditsUnlimited: boolean;
  /** @nullable */
  aiCreditsLimit?: PlanResponseDtoAiCreditsLimit;
  teamCollaboration: boolean;
  analyticsExport: boolean;
  createdAt: string;
}
