/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */

export type PostResponseDtoStatus = typeof PostResponseDtoStatus[keyof typeof PostResponseDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostResponseDtoStatus = {
  draft: 'draft',
  scheduled: 'scheduled',
  published: 'published',
  failed: 'failed',
  pending_approval: 'pending_approval',
} as const;
