/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */
import type { PostStatusResponseDtoStatus } from './postStatusResponseDtoStatus';
import type { PostStatusResponseDtoPublishedAt } from './postStatusResponseDtoPublishedAt';

export interface PostStatusResponseDto {
  id: number;
  status: PostStatusResponseDtoStatus;
  scheduledAt: string;
  /** @nullable */
  publishedAt?: PostStatusResponseDtoPublishedAt;
}
