/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */
import type { PostResponseDtoStatus } from './postResponseDtoStatus';
import type { PostResponseDtoPublishedAt } from './postResponseDtoPublishedAt';

export interface PostResponseDto {
  id: number;
  contentAr: string;
  contentEn?: string;
  status: PostResponseDtoStatus;
  isRecurring: boolean;
  /** @nullable */
  publishedAt?: PostResponseDtoPublishedAt;
  createdAt: string;
  updatedAt: string;
  scheduleAt: string;
}
