/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */
import type { RecurringPostDtoStatus } from './recurringPostDtoStatus';

export interface RecurringPostDto {
  /** Arabic content */
  contentAr: string;
  /** English content */
  contentEn?: string;
  /** First scheduled time (ISO) */
  scheduleAt: string;
  /** Status */
  status?: RecurringPostDtoStatus;
  /** Force recurring */
  isRecurring: boolean;
  /** Author ID */
  authorId: number;
  /** Team ID */
  teamId?: number;
  /** Social account IDs (multi-target) */
  socialAccountIds?: number[];
  /** Campaign ID */
  campaignId?: number;
  /** Template ID */
  templateId?: number;
}
