/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */

export interface ReschedulePostDto {
  /** New scheduled date/time */
  scheduleAt: string;
}
