/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */

export interface ResetPasswordDto {
  /** Password reset token */
  token: string;
  /**
   * New password
   * @minLength 6
   */
  newPassword: string;
}
