/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */

export type SubscriptionResponseDtoStatus = typeof SubscriptionResponseDtoStatus[keyof typeof SubscriptionResponseDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SubscriptionResponseDtoStatus = {
  active: 'active',
  canceled: 'canceled',
  past_due: 'past_due',
  trialing: 'trialing',
} as const;
