/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */
import type { SubscriptionResponseDtoStatus } from './subscriptionResponseDtoStatus';
import type { SubscriptionResponseDtoCanceledAt } from './subscriptionResponseDtoCanceledAt';
import type { SubscriptionResponseDtoPaymentGatewaySubscriptionId } from './subscriptionResponseDtoPaymentGatewaySubscriptionId';

export interface SubscriptionResponseDto {
  id: number;
  status: SubscriptionResponseDtoStatus;
  periodStartsAt: string;
  periodEndsAt: string;
  /** @nullable */
  canceledAt?: SubscriptionResponseDtoCanceledAt;
  /** @nullable */
  paymentGatewaySubscriptionId?: SubscriptionResponseDtoPaymentGatewaySubscriptionId;
  createdAt: string;
  updatedAt: string;
  planId: number;
}
