/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */

export interface SubscribeDto {
  /** Plan ID to subscribe to */
  planId: number;
  /** Payment method token or identifier */
  paymentMethod: string;
  /** Optional coupon code */
  couponCode?: string;
}
