/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */
import type { SubscriptionResponseDto } from './subscriptionResponseDto';
import type { SubscribeResponseDtoClientSecret } from './subscribeResponseDtoClientSecret';

export interface SubscribeResponseDto {
  subscription: SubscriptionResponseDto;
  /** @nullable */
  clientSecret?: SubscribeResponseDtoClientSecret;
}
