/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */

/**
 * New role for the team member
 */
export type UpdateMemberRoleDtoRole = typeof UpdateMemberRoleDtoRole[keyof typeof UpdateMemberRoleDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateMemberRoleDtoRole = {
  admin: 'admin',
  editor: 'editor',
  viewer: 'viewer',
} as const;
