/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */

export interface UpdatePreferencesDto {
  /** IANA timezone, e.g., America/New_York */
  timezone?: string;
  /** BCP 47 language tag, e.g., en or ar */
  language?: string;
  /** Locale for formatting, e.g., en-US or ar-EG */
  locale?: string;
  /** 12h or 24h clock format */
  timeFormat?: string;
}
