/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */

export type UpdateUserDtoTimeFormat = typeof UpdateUserDtoTimeFormat[keyof typeof UpdateUserDtoTimeFormat];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUserDtoTimeFormat = {
  '12h': '12h',
  '24h': '24h',
} as const;
