/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * The YSHAI backend API documentation. This API manages posts, teams, media, AI generation, moderation, analytics, billing, and more.
 * OpenAPI spec version: 1.0
 */
import type {
  LinkAccountResponseDto,
  LinkAccountWithTokensDto,
  MessageDto
} from '.././model';

import accountsControllerLinkMutator from '../../lib/orval-mutator';
import accountsControllerUnlinkMutator from '../../lib/orval-mutator';

/**
 * @summary Link Account
 */
export type accountsControllerLinkResponse201 = {
  data: LinkAccountResponseDto
  status: 201
}
    
export type accountsControllerLinkResponseSuccess = (accountsControllerLinkResponse201) & {
  headers: Headers;
};
;

export type accountsControllerLinkResponse = (accountsControllerLinkResponseSuccess)

export const getAccountsControllerLinkUrl = () => {


  

  return `/accounts`
}

export const accountsControllerLink = async (linkAccountWithTokensDto: LinkAccountWithTokensDto, options?: RequestInit): Promise<accountsControllerLinkResponse> => {
  
  return accountsControllerLinkMutator<accountsControllerLinkResponse>(getAccountsControllerLinkUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      linkAccountWithTokensDto,)
  }
);}


/**
 * @summary Unlink Account
 */
export type accountsControllerUnlinkResponse200 = {
  data: MessageDto
  status: 200
}
    
export type accountsControllerUnlinkResponseSuccess = (accountsControllerUnlinkResponse200) & {
  headers: Headers;
};
;

export type accountsControllerUnlinkResponse = (accountsControllerUnlinkResponseSuccess)

export const getAccountsControllerUnlinkUrl = (accountId: number,) => {


  

  return `/accounts/${accountId}`
}

export const accountsControllerUnlink = async (accountId: number, options?: RequestInit): Promise<accountsControllerUnlinkResponse> => {
  
  return accountsControllerUnlinkMutator<accountsControllerUnlinkResponse>(getAccountsControllerUnlinkUrl(accountId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


