/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * The YSHAI backend API documentation. This API manages posts, teams, media, AI generation, moderation, analytics, billing, and more.
 * OpenAPI spec version: 1.0
 */
import type {
  CreateWebhookDto,
  MessageDto,
  WebhooksControllerDeliveriesParams,
  WebhooksControllerRegister201
} from '.././model';

import { orvalMutator } from '../../lib/orval-mutator';

/**
 * @summary Register webhook
 */
export type webhooksControllerRegisterResponse201 = {
  data: WebhooksControllerRegister201
  status: 201
}
    
export type webhooksControllerRegisterResponseSuccess = (webhooksControllerRegisterResponse201) & {
  headers: Headers;
};
;

export type webhooksControllerRegisterResponse = (webhooksControllerRegisterResponseSuccess)

export const getWebhooksControllerRegisterUrl = () => {


  

  return `/webhooks`
}

export const webhooksControllerRegister = async (createWebhookDto: CreateWebhookDto, options?: RequestInit): Promise<webhooksControllerRegisterResponse> => {
  
  return orvalMutator<webhooksControllerRegisterResponse>(getWebhooksControllerRegisterUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createWebhookDto,)
  }
);}


/**
 * @summary List webhooks
 */
export type webhooksControllerListResponse200 = {
  data: void
  status: 200
}
    
export type webhooksControllerListResponseSuccess = (webhooksControllerListResponse200) & {
  headers: Headers;
};
;

export type webhooksControllerListResponse = (webhooksControllerListResponseSuccess)

export const getWebhooksControllerListUrl = () => {


  

  return `/webhooks`
}

export const webhooksControllerList = async ( options?: RequestInit): Promise<webhooksControllerListResponse> => {
  
  return orvalMutator<webhooksControllerListResponse>(getWebhooksControllerListUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Delete webhook
 */
export type webhooksControllerRemoveResponse200 = {
  data: MessageDto
  status: 200
}
    
export type webhooksControllerRemoveResponseSuccess = (webhooksControllerRemoveResponse200) & {
  headers: Headers;
};
;

export type webhooksControllerRemoveResponse = (webhooksControllerRemoveResponseSuccess)

export const getWebhooksControllerRemoveUrl = (webhookId: number,) => {


  

  return `/webhooks/${webhookId}`
}

export const webhooksControllerRemove = async (webhookId: number, options?: RequestInit): Promise<webhooksControllerRemoveResponse> => {
  
  return orvalMutator<webhooksControllerRemoveResponse>(getWebhooksControllerRemoveUrl(webhookId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * @summary List delivery attempts for a webhook
 */
export type webhooksControllerDeliveriesResponse200 = {
  data: void
  status: 200
}
    
export type webhooksControllerDeliveriesResponseSuccess = (webhooksControllerDeliveriesResponse200) & {
  headers: Headers;
};
;

export type webhooksControllerDeliveriesResponse = (webhooksControllerDeliveriesResponseSuccess)

export const getWebhooksControllerDeliveriesUrl = (webhookId: number,
    params?: WebhooksControllerDeliveriesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/webhooks/${webhookId}/deliveries?${stringifiedParams}` : `/webhooks/${webhookId}/deliveries`
}

export const webhooksControllerDeliveries = async (webhookId: number,
    params?: WebhooksControllerDeliveriesParams, options?: RequestInit): Promise<webhooksControllerDeliveriesResponse> => {
  
  return orvalMutator<webhooksControllerDeliveriesResponse>(getWebhooksControllerDeliveriesUrl(webhookId,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


