/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * The YSHAI backend API documentation. This API manages posts, teams, media, AI generation, moderation, analytics, billing, and more.
 * OpenAPI spec version: 1.0
 */
import type {
  AuthControllerForgotPasswordBody,
  AuthControllerResendVerificationBody,
  AuthControllerResetPasswordBody,
  AuthControllerVerifyEmailParams,
  LoginDto,
  MessageResponseDto,
  Promise,
  RefreshTokenDto,
  RegisterDto,
  TokensResponseDto
} from './model';



/**
 * @summary Register a new user
 */
export type authControllerRegisterResponse200 = {
  data: MessageResponseDto
  status: 200
}
    
export type authControllerRegisterResponseSuccess = (authControllerRegisterResponse200) & {
  headers: Headers;
};
;

export type authControllerRegisterResponse = (authControllerRegisterResponseSuccess)

export const getAuthControllerRegisterUrl = () => {


  

  return `/auth/register`
}

export const authControllerRegister = async (registerDto: RegisterDto, options?: RequestInit): Promise<authControllerRegisterResponse> => {
  
  const res = await fetch(getAuthControllerRegisterUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      registerDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: authControllerRegisterResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authControllerRegisterResponse
}


/**
 * @summary Login User
 */
export type authControllerLoginResponse200 = {
  data: MessageResponseDto
  status: 200
}
    
export type authControllerLoginResponseSuccess = (authControllerLoginResponse200) & {
  headers: Headers;
};
;

export type authControllerLoginResponse = (authControllerLoginResponseSuccess)

export const getAuthControllerLoginUrl = () => {


  

  return `/auth/login`
}

export const authControllerLogin = async (loginDto: LoginDto, options?: RequestInit): Promise<authControllerLoginResponse> => {
  
  const res = await fetch(getAuthControllerLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: authControllerLoginResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authControllerLoginResponse
}


/**
 * @summary Logout
 */
export type authControllerLogoutResponse200 = {
  data: string
  status: 200
}

export type authControllerLogoutResponse404 = {
  data: string
  status: 404
}
    
export type authControllerLogoutResponseSuccess = (authControllerLogoutResponse200) & {
  headers: Headers;
};
export type authControllerLogoutResponseError = (authControllerLogoutResponse404) & {
  headers: Headers;
};

export type authControllerLogoutResponse = (authControllerLogoutResponseSuccess | authControllerLogoutResponseError)

export const getAuthControllerLogoutUrl = () => {


  

  return `/auth/logout`
}

export const authControllerLogout = async ( options?: RequestInit): Promise<authControllerLogoutResponse> => {
  
  const res = await fetch(getAuthControllerLogoutUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: authControllerLogoutResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authControllerLogoutResponse
}


/**
 * @summary Forgot password
 */
export type authControllerForgotPasswordResponse200 = {
  data: string
  status: 200
}

export type authControllerForgotPasswordResponse404 = {
  data: string
  status: 404
}
    
export type authControllerForgotPasswordResponseSuccess = (authControllerForgotPasswordResponse200) & {
  headers: Headers;
};
export type authControllerForgotPasswordResponseError = (authControllerForgotPasswordResponse404) & {
  headers: Headers;
};

export type authControllerForgotPasswordResponse = (authControllerForgotPasswordResponseSuccess | authControllerForgotPasswordResponseError)

export const getAuthControllerForgotPasswordUrl = () => {


  

  return `/auth/forgot-password`
}

export const authControllerForgotPassword = async (authControllerForgotPasswordBody: AuthControllerForgotPasswordBody, options?: RequestInit): Promise<authControllerForgotPasswordResponse> => {
  
  const res = await fetch(getAuthControllerForgotPasswordUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      authControllerForgotPasswordBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: authControllerForgotPasswordResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authControllerForgotPasswordResponse
}


/**
 * @summary Reset password
 */
export type authControllerResetPasswordResponse200 = {
  data: Promise
  status: 200
}

export type authControllerResetPasswordResponse404 = {
  data: Promise
  status: 404
}
    
export type authControllerResetPasswordResponseSuccess = (authControllerResetPasswordResponse200) & {
  headers: Headers;
};
export type authControllerResetPasswordResponseError = (authControllerResetPasswordResponse404) & {
  headers: Headers;
};

export type authControllerResetPasswordResponse = (authControllerResetPasswordResponseSuccess | authControllerResetPasswordResponseError)

export const getAuthControllerResetPasswordUrl = () => {


  

  return `/auth/reset-password`
}

export const authControllerResetPassword = async (authControllerResetPasswordBody: AuthControllerResetPasswordBody, options?: RequestInit): Promise<authControllerResetPasswordResponse> => {
  
  const res = await fetch(getAuthControllerResetPasswordUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      authControllerResetPasswordBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: authControllerResetPasswordResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authControllerResetPasswordResponse
}


/**
 * @summary Verify user email via token
 */
export type authControllerVerifyEmailResponse200 = {
  data: string
  status: 200
}

export type authControllerVerifyEmailResponse404 = {
  data: string
  status: 404
}
    
export type authControllerVerifyEmailResponseSuccess = (authControllerVerifyEmailResponse200) & {
  headers: Headers;
};
export type authControllerVerifyEmailResponseError = (authControllerVerifyEmailResponse404) & {
  headers: Headers;
};

export type authControllerVerifyEmailResponse = (authControllerVerifyEmailResponseSuccess | authControllerVerifyEmailResponseError)

export const getAuthControllerVerifyEmailUrl = (params: AuthControllerVerifyEmailParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/auth/verify?${stringifiedParams}` : `/auth/verify`
}

export const authControllerVerifyEmail = async (params: AuthControllerVerifyEmailParams, options?: RequestInit): Promise<authControllerVerifyEmailResponse> => {
  
  const res = await fetch(getAuthControllerVerifyEmailUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: authControllerVerifyEmailResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authControllerVerifyEmailResponse
}


/**
 * @summary Resend email verification link
 */
export type authControllerResendVerificationResponse200 = {
  data: string
  status: 200
}

export type authControllerResendVerificationResponse404 = {
  data: string
  status: 404
}
    
export type authControllerResendVerificationResponseSuccess = (authControllerResendVerificationResponse200) & {
  headers: Headers;
};
export type authControllerResendVerificationResponseError = (authControllerResendVerificationResponse404) & {
  headers: Headers;
};

export type authControllerResendVerificationResponse = (authControllerResendVerificationResponseSuccess | authControllerResendVerificationResponseError)

export const getAuthControllerResendVerificationUrl = () => {


  

  return `/auth/resend-verification`
}

export const authControllerResendVerification = async (authControllerResendVerificationBody: AuthControllerResendVerificationBody, options?: RequestInit): Promise<authControllerResendVerificationResponse> => {
  
  const res = await fetch(getAuthControllerResendVerificationUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      authControllerResendVerificationBody,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: authControllerResendVerificationResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authControllerResendVerificationResponse
}


export type authControllerRefreshResponse200 = {
  data: TokensResponseDto
  status: 200
}
    
export type authControllerRefreshResponseSuccess = (authControllerRefreshResponse200) & {
  headers: Headers;
};
;

export type authControllerRefreshResponse = (authControllerRefreshResponseSuccess)

export const getAuthControllerRefreshUrl = () => {


  

  return `/auth/refresh`
}

export const authControllerRefresh = async (refreshTokenDto: RefreshTokenDto, options?: RequestInit): Promise<authControllerRefreshResponse> => {
  
  const res = await fetch(getAuthControllerRefreshUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      refreshTokenDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: authControllerRefreshResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as authControllerRefreshResponse
}


