/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * The YSHAI backend API documentation. This API manages posts, teams, media, AI generation, moderation, analytics, billing, and more.
 * OpenAPI spec version: 1.0
 */


/**
 * @summary List notifications for current user
 */
export type notificationsControllerListResponse200 = {
  data: void
  status: 200
}
    
export type notificationsControllerListResponseSuccess = (notificationsControllerListResponse200) & {
  headers: Headers;
};
;

export type notificationsControllerListResponse = (notificationsControllerListResponseSuccess)

export const getNotificationsControllerListUrl = () => {


  

  return `/notifications`
}

export const notificationsControllerList = async ( options?: RequestInit): Promise<notificationsControllerListResponse> => {
  
  const res = await fetch(getNotificationsControllerListUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: notificationsControllerListResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as notificationsControllerListResponse
}


/**
 * @summary Mark notification as read
 */
export type notificationsControllerMarkReadResponse200 = {
  data: void
  status: 200
}
    
export type notificationsControllerMarkReadResponseSuccess = (notificationsControllerMarkReadResponse200) & {
  headers: Headers;
};
;

export type notificationsControllerMarkReadResponse = (notificationsControllerMarkReadResponseSuccess)

export const getNotificationsControllerMarkReadUrl = (notificationId: number,) => {


  

  return `/notifications/${notificationId}/read`
}

export const notificationsControllerMarkRead = async (notificationId: number, options?: RequestInit): Promise<notificationsControllerMarkReadResponse> => {
  
  const res = await fetch(getNotificationsControllerMarkReadUrl(notificationId),
  {      
    ...options,
    method: 'PATCH'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: notificationsControllerMarkReadResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as notificationsControllerMarkReadResponse
}


/**
 * @summary Get unread notifications count
 */
export type notificationsControllerUnreadCountResponse200 = {
  data: void
  status: 200
}
    
export type notificationsControllerUnreadCountResponseSuccess = (notificationsControllerUnreadCountResponse200) & {
  headers: Headers;
};
;

export type notificationsControllerUnreadCountResponse = (notificationsControllerUnreadCountResponseSuccess)

export const getNotificationsControllerUnreadCountUrl = () => {


  

  return `/notifications/unread-count`
}

export const notificationsControllerUnreadCount = async ( options?: RequestInit): Promise<notificationsControllerUnreadCountResponse> => {
  
  const res = await fetch(getNotificationsControllerUnreadCountUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: notificationsControllerUnreadCountResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as notificationsControllerUnreadCountResponse
}


/**
 * @summary Mark all notifications as read
 */
export type notificationsControllerMarkAllReadResponse200 = {
  data: void
  status: 200
}
    
export type notificationsControllerMarkAllReadResponseSuccess = (notificationsControllerMarkAllReadResponse200) & {
  headers: Headers;
};
;

export type notificationsControllerMarkAllReadResponse = (notificationsControllerMarkAllReadResponseSuccess)

export const getNotificationsControllerMarkAllReadUrl = () => {


  

  return `/notifications/mark-all-read`
}

export const notificationsControllerMarkAllRead = async ( options?: RequestInit): Promise<notificationsControllerMarkAllReadResponse> => {
  
  const res = await fetch(getNotificationsControllerMarkAllReadUrl(),
  {      
    ...options,
    method: 'PATCH'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: notificationsControllerMarkAllReadResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as notificationsControllerMarkAllReadResponse
}


