/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * The YSHAI backend API documentation. This API manages posts, teams, media, AI generation, moderation, analytics, billing, and more.
 * OpenAPI spec version: 1.0
 */
import type {
  BulkCreatePostsDto,
  CreatePostDto,
  DraftPostDto,
  Post,
  PostsControllerBulkCreateFromCsvBody,
  RecurringPostDto,
  ReschedulePostDto,
  UpdatePostDto
} from './model';



/**
 * @summary Create a new post
 */
export type postsControllerCreateResponse201 = {
  data: Post
  status: 201
}

export type postsControllerCreateResponse404 = {
  data: void
  status: 404
}
    
export type postsControllerCreateResponseSuccess = (postsControllerCreateResponse201) & {
  headers: Headers;
};
export type postsControllerCreateResponseError = (postsControllerCreateResponse404) & {
  headers: Headers;
};

export type postsControllerCreateResponse = (postsControllerCreateResponseSuccess | postsControllerCreateResponseError)

export const getPostsControllerCreateUrl = () => {


  

  return `/posts`
}

export const postsControllerCreate = async (createPostDto: CreatePostDto, options?: RequestInit): Promise<postsControllerCreateResponse> => {
  
  const res = await fetch(getPostsControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createPostDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postsControllerCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postsControllerCreateResponse
}


/**
 * @summary Bulk create posts
 */
export type postsControllerBulkCreateResponse201 = {
  data: Post[]
  status: 201
}
    
export type postsControllerBulkCreateResponseSuccess = (postsControllerBulkCreateResponse201) & {
  headers: Headers;
};
;

export type postsControllerBulkCreateResponse = (postsControllerBulkCreateResponseSuccess)

export const getPostsControllerBulkCreateUrl = () => {


  

  return `/posts/bulk`
}

export const postsControllerBulkCreate = async (bulkCreatePostsDto: BulkCreatePostsDto, options?: RequestInit): Promise<postsControllerBulkCreateResponse> => {
  
  const res = await fetch(getPostsControllerBulkCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      bulkCreatePostsDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postsControllerBulkCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postsControllerBulkCreateResponse
}


/**
 * @summary Bulk create posts from CSV upload
 */
export type postsControllerBulkCreateFromCsvResponse201 = {
  data: Post[]
  status: 201
}
    
export type postsControllerBulkCreateFromCsvResponseSuccess = (postsControllerBulkCreateFromCsvResponse201) & {
  headers: Headers;
};
;

export type postsControllerBulkCreateFromCsvResponse = (postsControllerBulkCreateFromCsvResponseSuccess)

export const getPostsControllerBulkCreateFromCsvUrl = () => {


  

  return `/posts/bulk/csv`
}

export const postsControllerBulkCreateFromCsv = async (postsControllerBulkCreateFromCsvBody: PostsControllerBulkCreateFromCsvBody, options?: RequestInit): Promise<postsControllerBulkCreateFromCsvResponse> => {
    const formData = new FormData();
formData.append(`file`, postsControllerBulkCreateFromCsvBody.file)

  const res = await fetch(getPostsControllerBulkCreateFromCsvUrl(),
  {      
    ...options,
    method: 'POST'
    ,
    body: 
      formData,
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postsControllerBulkCreateFromCsvResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postsControllerBulkCreateFromCsvResponse
}


/**
 * @summary Create a recurring post
 */
export type postsControllerCreateRecurringResponse201 = {
  data: Post
  status: 201
}
    
export type postsControllerCreateRecurringResponseSuccess = (postsControllerCreateRecurringResponse201) & {
  headers: Headers;
};
;

export type postsControllerCreateRecurringResponse = (postsControllerCreateRecurringResponseSuccess)

export const getPostsControllerCreateRecurringUrl = () => {


  

  return `/posts/recurring`
}

export const postsControllerCreateRecurring = async (recurringPostDto: RecurringPostDto, options?: RequestInit): Promise<postsControllerCreateRecurringResponse> => {
  
  const res = await fetch(getPostsControllerCreateRecurringUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      recurringPostDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postsControllerCreateRecurringResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postsControllerCreateRecurringResponse
}


/**
 * @summary Create a draft post
 */
export type postsControllerCreateDraftResponse201 = {
  data: Post
  status: 201
}
    
export type postsControllerCreateDraftResponseSuccess = (postsControllerCreateDraftResponse201) & {
  headers: Headers;
};
;

export type postsControllerCreateDraftResponse = (postsControllerCreateDraftResponseSuccess)

export const getPostsControllerCreateDraftUrl = () => {


  

  return `/posts/draft`
}

export const postsControllerCreateDraft = async (draftPostDto: DraftPostDto, options?: RequestInit): Promise<postsControllerCreateDraftResponse> => {
  
  const res = await fetch(getPostsControllerCreateDraftUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      draftPostDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postsControllerCreateDraftResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postsControllerCreateDraftResponse
}


/**
 * @summary Update an existing post
 */
export type postsControllerUpdateResponse200 = {
  data: Post
  status: 200
}

export type postsControllerUpdateResponse404 = {
  data: void
  status: 404
}
    
export type postsControllerUpdateResponseSuccess = (postsControllerUpdateResponse200) & {
  headers: Headers;
};
export type postsControllerUpdateResponseError = (postsControllerUpdateResponse404) & {
  headers: Headers;
};

export type postsControllerUpdateResponse = (postsControllerUpdateResponseSuccess | postsControllerUpdateResponseError)

export const getPostsControllerUpdateUrl = (id: number,) => {


  

  return `/posts/${id}`
}

export const postsControllerUpdate = async (id: number,
    updatePostDto: UpdatePostDto, options?: RequestInit): Promise<postsControllerUpdateResponse> => {
  
  const res = await fetch(getPostsControllerUpdateUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updatePostDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postsControllerUpdateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postsControllerUpdateResponse
}


/**
 * @summary Delete a post (soft delete)
 */
export type postsControllerRemoveResponse200 = {
  data: void
  status: 200
}

export type postsControllerRemoveResponse404 = {
  data: void
  status: 404
}
    
export type postsControllerRemoveResponseSuccess = (postsControllerRemoveResponse200) & {
  headers: Headers;
};
export type postsControllerRemoveResponseError = (postsControllerRemoveResponse404) & {
  headers: Headers;
};

export type postsControllerRemoveResponse = (postsControllerRemoveResponseSuccess | postsControllerRemoveResponseError)

export const getPostsControllerRemoveUrl = (id: number,) => {


  

  return `/posts/${id}`
}

export const postsControllerRemove = async (id: number, options?: RequestInit): Promise<postsControllerRemoveResponse> => {
  
  const res = await fetch(getPostsControllerRemoveUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postsControllerRemoveResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postsControllerRemoveResponse
}


/**
 * @summary Reschedule a post
 */
export type postsControllerRescheduleResponse200 = {
  data: Post
  status: 200
}
    
export type postsControllerRescheduleResponseSuccess = (postsControllerRescheduleResponse200) & {
  headers: Headers;
};
;

export type postsControllerRescheduleResponse = (postsControllerRescheduleResponseSuccess)

export const getPostsControllerRescheduleUrl = (id: number,) => {


  

  return `/posts/${id}/reschedule`
}

export const postsControllerReschedule = async (id: number,
    reschedulePostDto: ReschedulePostDto, options?: RequestInit): Promise<postsControllerRescheduleResponse> => {
  
  const res = await fetch(getPostsControllerRescheduleUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      reschedulePostDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postsControllerRescheduleResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postsControllerRescheduleResponse
}


/**
 * @summary Publish a post immediately (enqueue job)
 */
export type postsControllerPublishNowResponse200 = {
  data: Post
  status: 200
}
    
export type postsControllerPublishNowResponseSuccess = (postsControllerPublishNowResponse200) & {
  headers: Headers;
};
;

export type postsControllerPublishNowResponse = (postsControllerPublishNowResponseSuccess)

export const getPostsControllerPublishNowUrl = (id: number,) => {


  

  return `/posts/${id}/publish`
}

export const postsControllerPublishNow = async (id: number, options?: RequestInit): Promise<postsControllerPublishNowResponse> => {
  
  const res = await fetch(getPostsControllerPublishNowUrl(id),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postsControllerPublishNowResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postsControllerPublishNowResponse
}


/**
 * @summary Get post status
 */
export type postsControllerStatusGetResponse200 = {
  data: void
  status: 200
}
    
export type postsControllerStatusGetResponseSuccess = (postsControllerStatusGetResponse200) & {
  headers: Headers;
};
;

export type postsControllerStatusGetResponse = (postsControllerStatusGetResponseSuccess)

export const getPostsControllerStatusGetUrl = (id: number,) => {


  

  return `/posts/${id}/status`
}

export const postsControllerStatusGet = async (id: number, options?: RequestInit): Promise<postsControllerStatusGetResponse> => {
  
  const res = await fetch(getPostsControllerStatusGetUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postsControllerStatusGetResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postsControllerStatusGetResponse
}


