/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * The YSHAI backend API documentation. This API manages posts, teams, media, AI generation, moderation, analytics, billing, and more.
 * OpenAPI spec version: 1.0
 */
import type {
  CreateTeamDto,
  InviteMemberDto,
  UpdateMemberRoleDto
} from './model';



/**
 * @summary Create a new team
 */
export type teamsControllerCreateResponse201 = {
  data: void
  status: 201
}
    
export type teamsControllerCreateResponseSuccess = (teamsControllerCreateResponse201) & {
  headers: Headers;
};
;

export type teamsControllerCreateResponse = (teamsControllerCreateResponseSuccess)

export const getTeamsControllerCreateUrl = () => {


  

  return `/teams`
}

export const teamsControllerCreate = async (createTeamDto: CreateTeamDto, options?: RequestInit): Promise<teamsControllerCreateResponse> => {
  
  const res = await fetch(getTeamsControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createTeamDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: teamsControllerCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as teamsControllerCreateResponse
}


/**
 * @summary Invite a member to the team
 */
export type teamsControllerInviteMemberResponse200 = {
  data: void
  status: 200
}
    
export type teamsControllerInviteMemberResponseSuccess = (teamsControllerInviteMemberResponse200) & {
  headers: Headers;
};
;

export type teamsControllerInviteMemberResponse = (teamsControllerInviteMemberResponseSuccess)

export const getTeamsControllerInviteMemberUrl = (teamId: number,) => {


  

  return `/teams/${teamId}/invite`
}

export const teamsControllerInviteMember = async (teamId: number,
    inviteMemberDto: InviteMemberDto, options?: RequestInit): Promise<teamsControllerInviteMemberResponse> => {
  
  const res = await fetch(getTeamsControllerInviteMemberUrl(teamId),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      inviteMemberDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: teamsControllerInviteMemberResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as teamsControllerInviteMemberResponse
}


/**
 * @summary Update a team member’s role
 */
export type teamsControllerUpdateMemberRoleResponse200 = {
  data: void
  status: 200
}
    
export type teamsControllerUpdateMemberRoleResponseSuccess = (teamsControllerUpdateMemberRoleResponse200) & {
  headers: Headers;
};
;

export type teamsControllerUpdateMemberRoleResponse = (teamsControllerUpdateMemberRoleResponseSuccess)

export const getTeamsControllerUpdateMemberRoleUrl = (teamId: number,
    memberId: number,) => {


  

  return `/teams/${teamId}/members/${memberId}`
}

export const teamsControllerUpdateMemberRole = async (teamId: number,
    memberId: number,
    updateMemberRoleDto: UpdateMemberRoleDto, options?: RequestInit): Promise<teamsControllerUpdateMemberRoleResponse> => {
  
  const res = await fetch(getTeamsControllerUpdateMemberRoleUrl(teamId,memberId),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateMemberRoleDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: teamsControllerUpdateMemberRoleResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as teamsControllerUpdateMemberRoleResponse
}


/**
 * @summary Remove a member from the team
 */
export type teamsControllerRemoveMemberResponse200 = {
  data: void
  status: 200
}
    
export type teamsControllerRemoveMemberResponseSuccess = (teamsControllerRemoveMemberResponse200) & {
  headers: Headers;
};
;

export type teamsControllerRemoveMemberResponse = (teamsControllerRemoveMemberResponseSuccess)

export const getTeamsControllerRemoveMemberUrl = (teamId: number,
    memberId: number,) => {


  

  return `/teams/${teamId}/members/${memberId}`
}

export const teamsControllerRemoveMember = async (teamId: number,
    memberId: number, options?: RequestInit): Promise<teamsControllerRemoveMemberResponse> => {
  
  const res = await fetch(getTeamsControllerRemoveMemberUrl(teamId,memberId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: teamsControllerRemoveMemberResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as teamsControllerRemoveMemberResponse
}


/**
 * @summary Approve a post for publishing
 */
export type teamsControllerApprovePostResponse201 = {
  data: void
  status: 201
}
    
export type teamsControllerApprovePostResponseSuccess = (teamsControllerApprovePostResponse201) & {
  headers: Headers;
};
;

export type teamsControllerApprovePostResponse = (teamsControllerApprovePostResponseSuccess)

export const getTeamsControllerApprovePostUrl = (teamId: number,
    postId: number,) => {


  

  return `/teams/${teamId}/posts/${postId}/approve`
}

export const teamsControllerApprovePost = async (teamId: number,
    postId: number, options?: RequestInit): Promise<teamsControllerApprovePostResponse> => {
  
  const res = await fetch(getTeamsControllerApprovePostUrl(teamId,postId),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: teamsControllerApprovePostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as teamsControllerApprovePostResponse
}


/**
 * @summary Reject a post
 */
export type teamsControllerRejectPostResponse201 = {
  data: void
  status: 201
}
    
export type teamsControllerRejectPostResponseSuccess = (teamsControllerRejectPostResponse201) & {
  headers: Headers;
};
;

export type teamsControllerRejectPostResponse = (teamsControllerRejectPostResponseSuccess)

export const getTeamsControllerRejectPostUrl = (teamId: number,
    postId: number,) => {


  

  return `/teams/${teamId}/posts/${postId}/reject`
}

export const teamsControllerRejectPost = async (teamId: number,
    postId: number, options?: RequestInit): Promise<teamsControllerRejectPostResponse> => {
  
  const res = await fetch(getTeamsControllerRejectPostUrl(teamId,postId),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: teamsControllerRejectPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as teamsControllerRejectPostResponse
}


/**
 * @summary List team audit logs
 */
export type teamsControllerListAuditLogsResponse200 = {
  data: void
  status: 200
}
    
export type teamsControllerListAuditLogsResponseSuccess = (teamsControllerListAuditLogsResponse200) & {
  headers: Headers;
};
;

export type teamsControllerListAuditLogsResponse = (teamsControllerListAuditLogsResponseSuccess)

export const getTeamsControllerListAuditLogsUrl = (teamId: number,) => {


  

  return `/teams/${teamId}/audit-logs`
}

export const teamsControllerListAuditLogs = async (teamId: number, options?: RequestInit): Promise<teamsControllerListAuditLogsResponse> => {
  
  const res = await fetch(getTeamsControllerListAuditLogsUrl(teamId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: teamsControllerListAuditLogsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as teamsControllerListAuditLogsResponse
}


