/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * Generated for Orval client
 * OpenAPI spec version: 1.0
 */
import type {
  AdminAuditLogResponseDto,
  AdminControllerAssignRole200,
  AdminControllerBanUser200,
  AdminUserResponseDto,
  AssignRoleDto
} from '.././models';


/**
 * @summary List users
 */
export type adminControllerListUsersResponse200 = {
  data: AdminUserResponseDto[]
  status: 200
}
    
export type adminControllerListUsersResponseSuccess = (adminControllerListUsersResponse200) & {
  headers: Headers;
};
;

export type adminControllerListUsersResponse = (adminControllerListUsersResponseSuccess)

export const getAdminControllerListUsersUrl = () => {


  

  return `http://localhost:5000/admin/users`
}

export const adminControllerListUsers = async ( options?: RequestInit): Promise<adminControllerListUsersResponse> => {
  
  const res = await fetch(getAdminControllerListUsersUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: adminControllerListUsersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as adminControllerListUsersResponse
}


/**
 * @summary Ban user
 */
export type adminControllerBanUserResponse200 = {
  data: AdminControllerBanUser200
  status: 200
}
    
export type adminControllerBanUserResponseSuccess = (adminControllerBanUserResponse200) & {
  headers: Headers;
};
;

export type adminControllerBanUserResponse = (adminControllerBanUserResponseSuccess)

export const getAdminControllerBanUserUrl = (id: number,) => {


  

  return `http://localhost:5000/admin/users/${id}/ban`
}

export const adminControllerBanUser = async (id: number, options?: RequestInit): Promise<adminControllerBanUserResponse> => {
  
  const res = await fetch(getAdminControllerBanUserUrl(id),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: adminControllerBanUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as adminControllerBanUserResponse
}


/**
 * @summary Assign role
 */
export type adminControllerAssignRoleResponse200 = {
  data: AdminControllerAssignRole200
  status: 200
}
    
export type adminControllerAssignRoleResponseSuccess = (adminControllerAssignRoleResponse200) & {
  headers: Headers;
};
;

export type adminControllerAssignRoleResponse = (adminControllerAssignRoleResponseSuccess)

export const getAdminControllerAssignRoleUrl = (id: number,) => {


  

  return `http://localhost:5000/admin/users/${id}/role`
}

export const adminControllerAssignRole = async (id: number,
    assignRoleDto: AssignRoleDto, options?: RequestInit): Promise<adminControllerAssignRoleResponse> => {
  
  const res = await fetch(getAdminControllerAssignRoleUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      assignRoleDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: adminControllerAssignRoleResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as adminControllerAssignRoleResponse
}


/**
 * @summary Audit logs
 */
export type adminControllerAuditLogsResponse200 = {
  data: AdminAuditLogResponseDto[]
  status: 200
}
    
export type adminControllerAuditLogsResponseSuccess = (adminControllerAuditLogsResponse200) & {
  headers: Headers;
};
;

export type adminControllerAuditLogsResponse = (adminControllerAuditLogsResponseSuccess)

export const getAdminControllerAuditLogsUrl = () => {


  

  return `http://localhost:5000/admin/audit-logs`
}

export const adminControllerAuditLogs = async ( options?: RequestInit): Promise<adminControllerAuditLogsResponse> => {
  
  const res = await fetch(getAdminControllerAuditLogsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: adminControllerAuditLogsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as adminControllerAuditLogsResponse
}


