import type { Metadata } from "next";
import { IBM_Plex_Sans_Arabic, Manrope } from "next/font/google";
import "../globals.css";
import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { routing } from '../i18n/routing'
import { notFound } from "next/navigation";
import { getMessages, getTranslations, setRequestLocale } from 'next-intl/server';
import { ThemeProvider } from "../components/theme-provider";
import { Navbar } from "./components/Navbar";
import { Toaster } from "../../components/ui/sonner"
import { apiClient } from "@/lib/api";
export const metadata: Metadata = {
  title: "YSHAI",
  description: "Generated by create next app",
};
type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};
const manrope = Manrope({
  subsets: ['latin']
})
// just for the streak
const ibm_Plex_Sans_Arabic = IBM_Plex_Sans_Arabic({
  weight: ['100', '200', '300', '400', '500', '600', '700'],
  subsets: ['arabic']
})
export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  setRequestLocale(locale)

  const messages = await getMessages();
  const t = await getTranslations({ locale, namespace: "Navbar" });
  const text: any = {
    logo: t("logo"),
    register: t("register"),
    login: t("login"),
    pricing: t("pricing"),
    about: t("about"),
    features: t("features"),
    dashboard: t("dashboard"),
    logout: t("logout"),
  }
  let user = null;

  try {
    user = await apiClient('/users/me', { credentials: 'include' });
    console.log('Fetched user data:', user);
  } catch (err) {
    console.log('Error fetching user data:', err);
  }
  return (
    <html lang={locale} dir={locale === 'ar' ? 'rtl' : 'ltr'}>
      <body
        className={`${manrope.className}  ${ibm_Plex_Sans_Arabic.className} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <Navbar text={text} user={user} />
            {children}
            <Toaster position="bottom-right" />
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
