import type { Metadata } from "next";
import { IBM_Plex_Sans_Arabic, Manrope } from "next/font/google";
import "../globals.css";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { routing } from "../i18n/routing";
import { notFound } from "next/navigation";
import { getMessages, setRequestLocale } from "next-intl/server";
import { ThemeProvider } from "../components/theme-provider";
import { Navbar } from "./components/Navbar";
import { Toaster } from "../../components/ui/sonner";
import { extractNavbarText } from "../i18n/extractTexts";
import { NavbarWrapper } from "./components/NavbarWrapper";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "YSHAI",
  description: "Generated by create next app",
};
type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};
const manrope = Manrope({
  subsets: ["latin"],
});
// just for the streak
const ibm_Plex_Sans_Arabic = IBM_Plex_Sans_Arabic({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  subsets: ["arabic"],
});

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}
export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  setRequestLocale(locale);
  const text = await extractNavbarText(locale);

  const messages = await getMessages();

  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <body
        className={`${manrope.className}  ${ibm_Plex_Sans_Arabic.className} scroll-smooth antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NextIntlClientProvider locale={locale} messages={messages}>
            <Suspense fallback={<div>loading...</div>}>
              <NavbarWrapper>
                <Navbar text={text} />
              </NavbarWrapper>
            </Suspense>
            {children}
            <Toaster position="bottom-right" />
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
