/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * YSHAI API
 * The YSHAI backend API documentation. This API manages posts, teams, media, AI generation, moderation, analytics, billing, and more.
 * OpenAPI spec version: 1.0
 */
import type {
  UpdatePreferencesDto,
  UpdateUserDto,
  UserResponseDto
} from '.././model';

import usersControllerGetProfileMutator from '../../lib/orval-mutator';
import usersControllerUpdateProfileMutator from '../../lib/orval-mutator';
import usersControllerUpdatePreferencesMutator from '../../lib/orval-mutator';

/**
 * @summary Get current user using JWT
 */
export type usersControllerGetProfileResponse200 = {
  data: UserResponseDto
  status: 200
}

export type usersControllerGetProfileResponse404 = {
  data: void
  status: 404
}

export type usersControllerGetProfileResponseSuccess = (usersControllerGetProfileResponse200) & {
  headers: Headers;
};
export type usersControllerGetProfileResponseError = (usersControllerGetProfileResponse404) & {
  headers: Headers;
};

export type usersControllerGetProfileResponse = (usersControllerGetProfileResponseSuccess | usersControllerGetProfileResponseError)

export const getUsersControllerGetProfileUrl = () => {




  return `/users/me`
}

export const usersControllerGetProfile = async (options?: RequestInit): Promise<usersControllerGetProfileResponse> => {

  return usersControllerGetProfileMutator<usersControllerGetProfileResponse>(getUsersControllerGetProfileUrl(),
    {
      ...options,
      method: 'GET'


    }
  );
}


/**
 * @summary Update current user using JWT
 */
export type usersControllerUpdateProfileResponse200 = {
  data: UserResponseDto
  status: 200
}

export type usersControllerUpdateProfileResponse404 = {
  data: void
  status: 404
}

export type usersControllerUpdateProfileResponseSuccess = (usersControllerUpdateProfileResponse200) & {
  headers: Headers;
};
export type usersControllerUpdateProfileResponseError = (usersControllerUpdateProfileResponse404) & {
  headers: Headers;
};

export type usersControllerUpdateProfileResponse = (usersControllerUpdateProfileResponseSuccess | usersControllerUpdateProfileResponseError)

export const getUsersControllerUpdateProfileUrl = () => {




  return `/users/me`
}

export const usersControllerUpdateProfile = async (updateUserDto: UpdateUserDto, options?: RequestInit): Promise<usersControllerUpdateProfileResponse> => {

  return usersControllerUpdateProfileMutator<usersControllerUpdateProfileResponse>(getUsersControllerUpdateProfileUrl(),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(
        updateUserDto,)
    }
  );
}


/**
 * @summary Update current user preferences using JWT
 */
export type usersControllerUpdatePreferencesResponse200 = {
  data: void
  status: 200
}

export type usersControllerUpdatePreferencesResponseSuccess = (usersControllerUpdatePreferencesResponse200) & {
  headers: Headers;
};
;

export type usersControllerUpdatePreferencesResponse = (usersControllerUpdatePreferencesResponseSuccess)

export const getUsersControllerUpdatePreferencesUrl = () => {




  return `/users/me/preferences`
}

export const usersControllerUpdatePreferences = async (updatePreferencesDto: UpdatePreferencesDto, options?: RequestInit): Promise<usersControllerUpdatePreferencesResponse> => {

  return usersControllerUpdatePreferencesMutator<usersControllerUpdatePreferencesResponse>(getUsersControllerUpdatePreferencesUrl(),
    {
      ...options,
      method: 'PUT',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(
        updatePreferencesDto,)
    }
  );
}


